spring:
  application:
    name: spring-ai-tutorial
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_ai_tutorial
    username: postgres
    password: admin1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  ai:
    model:
      chat: ollama
    ollama:
      base-url: http://localhost:11434 # ollama default url
      init:
        pull-model-strategy: never # 모델이 없는 경우 전략
        timeout: 1m # 모델 pull 또는 초기화 대기 시간
        max-retries: 0 # model 초기화 실패 시 재시도 횟수
        chat:
          include: true # chat model bean 생성 여부
      chat:
        model: gemma4 # gemma3는 tool calling을 지원하지 않아서 모델 변경
#        format: json
        keep_alive: 5m
        memory:
          repository:
            jdbc:
              initialize-schema: never

#  ai:
#    openai:
#      api-key: open-ai-test-key
#    huggingface:
#      chat:
#        api-key: ${HUGGINGFACE_API_KEY}
#        url: https://api-inference.huggingface.co/models/Qwen/Qwen2.5-7B-Instruct