spring:
  application:
    name: spring-ai-tutorial
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_ai_tutorial?serverTimezone=UTC&useSSL=false
    username: root
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    model:
      chat: ollama
    ollama:
      base-url: http://localhost:11434 # ollama default url
      init:
        pull-model-strategy: never # 모델이 없는 경우 전략
        timeout: 1m # 모델 pull 또는 초기화 대기 시간
        max-retries: 0 # model 초기화 실패 시 재시도 횟수
        chat:
          include: true # chat model bean 생성 여부
      chat:
        model: gemma3
#        format: json
        keep_alive: 5m
        memory:
          repository:
            jdbc:
              initialize-schema: never

#  ai:
#    openai:
#      api-key: open-ai-test-key
#    huggingface:
#      chat:
#        api-key: ${HUGGINGFACE_API_KEY}
#        url: https://api-inference.huggingface.co/models/Qwen/Qwen2.5-7B-Instruct